import { MoonIcon, SunIcon } from '@chakra-ui/icons'
import {
  Box,
  ButtonGroup,
  Flex,
  Heading,
  IconButton,
  Link,
  Spacer,
  useColorMode,
} from '@chakra-ui/react'
import { useSession } from 'next-auth/react'
import Head from 'next/head'
import NextLink from 'next/link'
import { type ReactNode } from 'react'
import { SignInModal } from './sign-in-modal'
import { UserDropdown } from './user-dropdown'

export default function Layout({ children }: { children: ReactNode }) {
  const { data: session, status } = useSession()
  const { colorMode, toggleColorMode } = useColorMode()

  // sign in modal with signIn("google");

  return (
    <div>
      <Head>
        <title>Flowtastic</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* Navbar */}
      <Flex w='full' p={4} minWidth="max-content" alignItems="center" gap="2">
        <Link _hover={{ textDecoration: 'none' }} as={NextLink} href="/">
          <Box p="2">
            <Heading size="md">Flowtastic</Heading>
          </Box>
        </Link>
        <Spacer />
        <ButtonGroup gap="2">
          <IconButton
            aria-label="toggleColorMode"
            onClick={toggleColorMode}
            icon={colorMode === 'light' ? <MoonIcon /> : <SunIcon />}
          />
          {!session && status !== 'loading' ? (
            <SignInModal />
          ) : (
            <UserDropdown />
          )}
        </ButtonGroup>
      </Flex>
      <main>{children}</main>
      {/* Footer */}
    </div>
  )
}
